# -*- coding: utf-8 -*-
"""Analysis_cost_apartments3.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nhEk4lO7tjx4XlnYruv75TZXARVdVK8D

# **Data analysis/Analysis cost apartments**

# **Библиотеки**
"""

import re # регулярные выражения

# Статический вывод графики (графики отображаются в той ячейке, в которой используется plt.show())
import pandas as pd # Импортируем библиотеку обработки и анализа данных pandas
import matplotlib.pyplot as plt # Импортируем модуль pyplot библиотеки matplotlib для построения графиков
import datetime # Импортируем модуль datetime для обработки данных в формете даты
import numpy as np # Импортируем библиотеку numpy
from google.colab import files # Импортируем библиотеку files для работы с файлами

"""# **Загружаем базу**"""

# Для загрузки данных используем drive
from google.colab import drive
drive.mount('/content/drive')

from google.colab import drive
drive.mount('/content/drive')

moscow_df = pd.read_csv('/content/drive/My Drive/moscow.csv', sep=';')# Путь к файлу

moscow_df

#●	Убираем строки “Для заметок”
moscow_df = moscow_df[moscow_df['Комнат'] != 'Для заметок:'] #Оставляем в таблице только те строки, у которых в графе "Комнат" нет записи "Для заметок"
moscow_df #Смотрим результат

#●	Убираем строки “ГРМ” и “Примечания”
del moscow_df['Примечание'] #Удаляем "Примечание
del moscow_df['ГРМ'] # Удаляем "ГРМ"
del moscow_df['Источник'] #Удаляем "Источник"

moscow_df #Смотрим результат

del moscow_df['Дата'] #Удаляем колонку "Дата"
moscow_df #Смотрим результат

#●	Для столбца “Балкон” добавляем категорию “Отсутствует” (вместо NaN)
moscow_df['Балкон'] = moscow_df['Балкон'].replace(np.nan, 'Отсутствует')

moscow_df

#●	Значения столбца “Бонус агенту” переводим в тысячи рублей,а пустые значения заполните нулями 
moscow_df['Бонус агенту'] = moscow_df['Бонус агенту'].replace(np.nan, 0)
moscow_df.head(1150)